### ISSUE TITLE
Update to Angular 12

### ISSUE THREAD

**Issue by beeing** [tavwizard/wngcc#1]
Hi, thanks for this tool.

Can you update it to latest version as ng12?

Also there is error as below:
```
 Cannot read property 'ngccVersion' of undefined
   at /node_modules/wngcc/dist/package-finder.js:34:21
   at Array.forEach (<anonymous>)
   at loadPackages (/node_modules/wngcc/dist/package-finder.js:33:11)
```

Thanks in advance.

**Comment by tavwizard** [comment]
version 1.1.3 and 1.2.1 tested with ng12
